### ISSUE TITLE
UnboundLocalError: local variable 'soup' referenced before assignment

### ISSUE THREAD

**Issue by gr3ym1nd** [RedVirus0/BlackDir#2]
Hi,
I receive with the call of BlackDir with the following call

python3 BlackDir.py --dork inurl:?id=

the error message:
Traceback (most recent call last):
  File "BlackDir.py", line 792, in <module>
    dorks(dork, site, text)
  File "BlackDir.py", line 467, in dorks
    for g in soup.find_all('div', class_='r'):
UnboundLocalError: local variable 'soup' referenced before assignment

I tried without a proxy, tried with proxychains and through a fixed configured VPN. The error message is always the same.
If I assign soup directly in BlackDir.py above the line 464, i don't get the error message anymore, but no results from Google come in either.

All requirements are successfully installed.
Python 3.82

**Comment by JehadAlqurashi** [comment]
don't use proxy this is error because use proxy

**Comment by JehadAlqurashi** [comment]
![Screenshot 2020-09-25 18:45:02](https://user-images.githubusercontent.com/46041727/94322046-5ae2a400-ff5f-11ea-87d3-cd1367d0b211.png)
